name: Build SMPlayer on Windows with MSVC

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: win64_msvc2019_64

      - name: Install Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build smplayer
        run: |
            .\getrev.cmd
            cd zlib
            nmake -f win32/Makefile.msc
            cd ..
            cd src
            lrelease smplayer.pro
            qmake
            nmake
